variable "asg_policy_up" {}
variable "asg_policy_down" {}
variable "asg_group_name" {}
variable "alarm_nameUP" {}
variable "comparison_operatorUP" {}
variable "evaluation_periodsUP" {}
variable "metric_nameUP" {}
variable "namespaceUP" {}
variable "periodUP" {}
variable "statisticUP" {}
variable "thresholdUP" {}
variable "alarm_nameDOWN" {}
variable "comparison_operatorDOWN" {}
variable "evaluation_periodsDOWN" {}
variable "metric_nameDOWN" {}
variable "namespaceDOWN" {}
variable "periodDOWN" {}
variable "statisticDOWN" {}
variable "thresholdDOWN" {}
variable "alarm_descriptionUP" {}
variable "alarm_descriptionDOWN" {}